# Generated by Django 5.0.6 on 2024-06-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_body_style'),
        ('payments', '0003_rename_car_id_payment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
