# Generated by Django 5.0.6 on 2024-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_car_alter_payment_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
