# Generated by Django 5.0.6 on 2024-06-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_phone_alter_payment_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
