# Generated by Django 5.0.6 on 2024-06-23 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
