# Generated by Django 5.0.6 on 2024-06-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
