# Generated by Django 5.0.6 on 2024-07-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refunds',
            old_name='car_id',
            new_name='car_refund_id',
        ),
        migrations.RenameField(
            model_name='refunds',
            old_name='user_id',
            new_name='user_refund_id',
        ),
    ]
