# Generated by Django 5.0.6 on 2024-07-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_car_id_refunds_car_refund_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refunds',
            name='trial_date',
        ),
    ]
